before_script:
  - curl -sL https://deb.nodesource.com/setup_6.x | bash -
  - apt-get install -y nodejs
  - which node


stages:
  - build
  - test
  - deploy


.script: &build_script
  - npm -v
  - cd  /builds/jawahar273/bm-client
  - npm start

job1:
  stage: build
  script: *build_script
  only: master