before_script:
  - curl -sL https://deb.nodesource.com/setup_6.x | bash -
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt-get update
  - apt-get install -y nodejs
  - apt-get install -y yarn
  - curl -LO https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - which node
  - pip3 install selenium

stages:
  - build
  - test
  - deploy


.script: &build_script
  - yarn -v
  - cd  /builds/jawahar273/bm-client
  - yarn install
  - yarn add  @angular-devkit/core@0.0.28 --save-dev
  - mkdir public
  - yarn build -op public -bh /bm-client/ && yarn run angular-cli-ghpages --dir public

page_to_gitlab:
  stage: build
  script: *build_script
  artifacts:
    paths:
    - public
  only:
  - master


test_with_selenium:
  stage: test
  only: master
  script: python3 -version
  allow-fail: true
  artifacts:
    paths:
    - public