before_script:
  - curl -sL https://deb.nodesource.com/setup_6.x | bash -
  - apt-get install -y nodejs
  - which node


stages:
  - build
  - test
  - deploy


.script: &build_script
  - npm -v

simple_test: